
version: "3.9"
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  sandra-backend:
    build: ./sandra-backend
    ports:
      - "80:3001"
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama:
